name: Linux

on:
  push:
    paths:
      - '**.zig'
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: master
      
      - name: Install dependences
        run: |
            sudo apt update
            sudo apt install libvlc-dev -y

      - name: Build
        run: zig build -fsummary -freference-trace
